# Generated by Django 5.1.2 on 2024-11-20 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gmail', models.EmailField(max_length=255)),
                ('face_hash', models.CharField(max_length=1024)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.workstation')),
            ],
        ),
    ]
