# Generated by Django 5.1.4 on 2025-01-01 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_time',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('additional', models.JSONField()),
                ('common_break_time', models.TextField(max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spy_app.worker')),
            ],
        ),
    ]
