# Generated by Django 5.1.4 on 2025-01-01 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy_app', '0002_worker_face_image_worker_work_time_dailyworkreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='face_hash',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_time',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
