# Generated by Django 5.1.4 on 2025-01-02 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy_app', '0003_alter_worker_face_hash_alter_worker_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyworkreport',
            name='data',
        ),
        migrations.AddField(
            model_name='dailyworkreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
