# Generated by Django 5.1.4 on 2025-01-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy_app', '0006_alter_dailyworkreport_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyworkreport',
            name='additional',
            field=models.TextField(max_length=30000, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkreport',
            name='finish_time',
            field=models.TimeField(),
        ),
    ]
