# Generated by Django 5.1.4 on 2025-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy_app', '0007_alter_dailyworkreport_additional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyworkreport',
            name='common_work_time',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dailyworkreport',
            name='work_efficiency',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyworkreport',
            name='common_break_time',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
