# Generated by Django 5.1.4 on 2025-01-04 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy_app', '0008_dailyworkreport_common_work_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserHistoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.TextField(max_length=32)),
                ('title', models.TextField(max_length=128)),
                ('url', models.TextField(max_length=64)),
                ('time', models.TextField(max_length=32)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spy_app.worker')),
            ],
        ),
    ]
