# Generated by Django 5.1.2 on 2024-12-29 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authtoken',
            name='token',
        ),
        migrations.AddField(
            model_name='authtoken',
            name='active',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='jwt',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
