# Generated by Django 5.1.2 on 2024-12-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_authtoken_token_authtoken_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
