# Generated by Django 5.1.2 on 2024-12-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_alter_authtoken_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authorization.workstation'),
        ),
    ]
